name: release

on:
  push:
    branches:
      - 2022.9.x-feature-build-api-docs

jobs:
  release-docker:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}

    steps:
      - run: echo "BUILD_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Checkout corteza-js
        uses: actions/checkout@v3
        with:
          repository: cortezaproject/corteza-js
          path: corteza-js
      - uses: docker/login-action@v1
        if: ${{ !env.ACT }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build corteza-js api docs
        run: |
          cd corteza-js
          yarn add typescript@4.7.4
          yarn add typedoc@0.23.17
          LATEST=$(git tag -l | grep 2022.9 | sort | tail -n 1) && \
            git checkout ${LATEST} && \
            npx typedoc --name "Corteza JS 2022.9" --hideGenerator --skipErrorChecking --out corteza-api-docs/2022.9 src/api-clients/index.ts
          LATEST=$(git tag -l | grep 2022.3 | sort | tail -n 1) && \
            git checkout ${LATEST} && \
            npx typedoc --name "Corteza JS 2022.3" --hideGenerator --skipErrorChecking --out corteza-api-docs/2022.3 src/api-clients/index.ts
          LATEST=$(git tag -l | grep 2021.9 | sort | tail -n 1) && \
            git checkout ${LATEST} && \
            npx typedoc --name "Corteza JS 2021.9" --hideGenerator --skipErrorChecking --out corteza-api-docs/2021.9 src/api-clients/index.ts

      - run: docker build --build-arg ALGOLIA_APP_ID="$ALGOLIA_APP_ID" --build-arg ALGOLIA_API_KEY="$ALGOLIA_API_KEY" --build-arg ALGOLIA_INDEX_NAME="$ALGOLIA_INDEX_NAME" -t cortezaproject/corteza-docs:2022.9.1-apidocs .
      - run: docker push cortezaproject/corteza-docs:2022.9.1-apidocs
      #   if: ${{ !env.ACT }}
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   if: always()
        # with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          # limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          # limit-access-to-users: petergrlica
